### ISSUE TITLE
Consider systematically recommending labels on landmark sections?

### ISSUE THREAD

**Issue by rdeltour** [daisy/kb#3]
Some sections can be identified as landmarks using DPUB roles (e.g. `dpub-chapter`, `dpub-part`). When this is the case, shouldn’t we recommend to systematically provide markup to define the accessible name of the section?

ARIA says for the [`region` role](https://www.w3.org/TR/wai-aria-1.1/#region):

> Authors MUST give each element with role region a brief label that describes the purpose of the content in the region. Authors SHOULD reference a visible label with aria-labelledby if a visible label is present. Authors SHOULD include the label inside of a heading whenever possible.

This shouldn’t be any different for the DPUB landmarks.

So we should recommend:

- set `aria-labelledby` when the section has a heading
- set `aria-label` otherwise

Also, in case the DPUB role isn’t supported by a UA+AT, we could recommend:

- using a `section` element (as we currently do) OR alternatively using a fallback `region` role (as a second ARIA role, for the UA+AT combinations that support this pattern, with a caveat that not all do). This, in combination with the label, will make the section a region landmark (which is a reasonable fallback for the DPUB landmarks).

See also [ARIA13](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/ARIA13).

**Comment by rdeltour** [comment]
RIght there are two different things:

- recommending `aria-label(ledby)` on sections as a _fallback_ for when the DPUB term isn’t supported

and

- figuring out what happens when there’s no accessible name on a DPUB landmark (which is perhaps a spec issue indeed)

**Comment by mattgarrish** [comment]
Okay, so what I've learned is that accessible names are not required for landmarks. They're useful, especially when there are a lot of the same landmarks like we may have with chapters, but the label just adds extra context. The landmarks will still be available to navigate to.

The section element with is a special case because it's becoming like div, so unless it has an accessible name it won't map to a landmark (i.e., is not treated as role="region".

In other words, adding a label is a good practice, but it's secondary to applying the correct DPUB-ARIA landmark. When implemented, a section with only a DPUB-ARIA landmark will still be a landmark, independent of the section element guidance, which is about the implied semantic.

It won't be the case that DPUB-ARIA landmark roles without an explicit label won't appear in the landmarks but sections with aria-label will. Both will be available, but the untitled sections may have more meaningful names attached to them.

Makes sense?

**Comment by mattgarrish** [comment]
Also, region is a special case in requiring an accessible name. The landmark role definition does not require one, and most landmarks inherit that setting.

**Comment by rdeltour** [comment]
> When implemented, a section with only a DPUB-ARIA landmark will still be a landmark, independent of the section element guidance, which is about the implied semantic.

The key thing here is in “_when implemented_”. My last point in the opening post was that where DPUB ARIA isn’t accessibility supported (like on Edge, where DPUB AAM is only [under consideration](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/digitalpublishingaccessibilityapimappings/), a region landmark is an appropriate fallback. Enabling this fallback on sections is just a matter of adding an ARIA label: it’s not very costly, and it certainly doesn’t hurt when DPUB ARIA is supported… so why not recommending that as a safety net?

**Comment by mattgarrish** [comment]
Right, if we recommend always labelling DPUB-ARIA landmarks, then we don't need to concern people with explicit fallback roles. I still think that's best practice, as it keeps things simple. I was only elaborating on my own question of what happens when there is a landmark and it doesn't have an accessible name.

**Comment by rdeltour** [comment]
> if we recommend always labelling DPUB-ARIA landmarks, then we don't need to concern people with explicit fallback roles

Correct (assuming DPUB landmarks are used on `section` elements, which is our recommendation so we’re consistent).

> I still think that's best practice, as it keeps things simple. 

👍

**Comment by mattgarrish** [comment]
I've added a faq section to the roles page as a start:
http://kb.daisy.org/publishing/docs/html/roles.html#faq

I was going to write it out in the explanation, but I doubt people read those in any detail so this should highlight the issues a bit better.

**Comment by mattgarrish** [comment]
Closing this issue as it also looks like it's been addressed now.
