### ISSUE TITLE
Suggestion for accessMode entry

### ISSUE THREAD

**Issue by marisademeglio** [daisy/kb#30]
I was recently troubleshooting an EPUB that had this entry:
`<meta name="schema:accessMode" content="textual,visual"/>`

It was getting flagged by Ace as an incorrect value but I couldn't find which spec said so. I looked in the [KB](https://kb.daisy.org/publishing/docs/metadata/schema.org/accessMode.html), [schema.org definitions](https://schema.org/accessMode), that [w3c wiki page](https://www.w3.org/wiki/WebSchemas/Accessibility) that always comes up, a [document by IMS Global](http://www.imsglobal.org/accessibility/afav3p0pd//AfA3p0_DRDinfoModel_v1p0pd.html#toc-7), and [EPUB Accessibility 1.0](http://idpf.org/epub/a11y/accessibility.html#sec-disc-package). There were some references to allowing multiple values but no examples, and nothing that disallowed the above syntax. And as `accessModeSufficient` is fine with something like `textual,visual`, it seems like a fair assumption that it would be ok for `accessMode` too. But I wanted definitive confirmation.  

Finally on [this page](http://idpf.org/epub/a11y/techniques/techniques.html#sec-discovery), it says that the syntax should be:
```
<meta property="schema:accessMode">textual</meta>
<meta property="schema:accessMode">visual</meta>
```

Do you think it's possible to add an example like this to the KB? I think users would find it really helpful. If it took me (a developer very familiar with EPUB accessibility) 20 minutes to find the right info in the current set of documents, it may take someone else much longer.

**Comment by mattgarrish** [comment]
You didn't check the techniques??? http://idpf.org/epub/a11y/techniques/techniques.html#meta-001 ;)

Seriously, though, agree completely. When I chopped the former oversized page on all the properties up I lost that bit. You have to go back to the overview page to see a full example with them split out.

FYI, the reason why we don't recommend a single property with a list is because there isn't a great way to formalize the structure of the value in schema.org (i.e., whether it's comma or space separated or something else) which makes parsing more complicated (it's also confusing with accessModeSufficient, where we had to resort to a comma-separated list because we don't have nested metadata in epub).

**Comment by marisademeglio** [comment]
The techniques doc is where I finally found it! The clarification there is great, just had to locate it amidst all the other documentation. Publishing metadata generally makes my head spin.

**Comment by mattgarrish** [comment]
LOL, I didn't even check the link. I thought you were referring back to one of the earlier docs.
