### ISSUE TITLE
KB display issue

### ISSUE THREAD

**Issue by ThomasR128** [daisy/kb#53]
Very much like the late-April redesign. Just wanted to point out a (CSS-related?) display issue: On Safari 15.5 (Mac OS 12.4) the sidebar overlaps the navigation menu:

<img width="603" alt="Captura de Pantalla 2022-05-28 a las 14 44 58" src="https://user-images.githubusercontent.com/64253366/170826276-67b21f2a-3d4f-4cc2-98d1-63ba225b1b86.png">

This does not occur on Firefox. No idea how Chrome behaves – I’m not voluntarily installing spyware.

**Comment by mattgarrish** [comment]
Hm, that is weird. I only have an ipad for checking safari, but it's working as expected.

Since the sidebar is a positioned element, I've added z-index: -1 to its css to see if that pushes it behind the header. It's the only thing I can think of right now given how specific the issue is. Let me know if it's made any difference.

**Comment by ThomasR128** [comment]
Solved on Safari 15.5 (Mac OS 12.4) which is still the latest version. On my iPad it also looks fine, but I only checked _after_ your fix. Webkit intricacies, obviously…

<img width="645" alt="Captura de Pantalla 2022-06-17 a las 17 13 15" src="https://user-images.githubusercontent.com/64253366/174327371-e01d23a0-1311-43a6-ac3f-7e76ec8c40d4.png">

**Comment by mattgarrish** [comment]
Always the way that you still get some quirk on some browser on some platform.

Thanks for letting me know about that one! Glad it wasn't too painful a fix... 😄

**Comment by ThomasR128** [comment]
I’m afraid I have to reopen this issue. Since adding the z-index, the links in the side bar are no longer operative. Sorry that I yelled “solved” too early. Affects:

- Safari on iOS 15.5 (iPhone) and iPadOS 15.5 (iPad)
- Safari Safari 15.5 (MacOS 12.4)
- Firefox 101.0.1 (MacOS 12.4)

Which made the issue worse overall … 😕 … on a positive note, it _does_ look better than before.

**Comment by mattgarrish** [comment]
Thanks for the update. It looks like the problem comes from calculating the header height and trying to back up the content to align nicely with it, though why only Macs get a different result is beyond me. Rather than do that, I've tweaked the layout so that it isn't necessary; the nav is parallel to both the page header and content.

Everything still looks right on the browsers I can access, but let me know if there's still an issue on Macs.

**Comment by ThomasR128** [comment]
Good news: The site looks correct on Safari

![Captura de Pantalla 2022-06-25 a las 9 27 41](https://user-images.githubusercontent.com/64253366/175763506-0a042c94-8ff7-4ce0-b2d5-1ce22a45cd9f.png)

and, more importantly, the links are working again on:

- Safari on iOS 15.5 (iPhone) and iPadOS 15.5 (iPad) – Webkit
- Safari 15.5 (MacOS 12.4) – Webkit
- Firefox 101.0.1 (MacOS 12.4) – Gecko/WebRender
- Opera 87.0 (MacOS 12.4) – Chromium/Blink (should also cover Chrome, Edge, etc.)

This covers all the major rendering engines.

> why only Macs get a different result is beyond me

I’m pretty sure it’s not Mac as such, since Firefox on Mac never had the issue. It’s probably Webkit-related which is only used in Safari and all iOS Browsers, and funnily enough, only the desktop version appears to have been affected since you didn’t have the initial issue on your iPad.
