### ISSUE TITLE
Repetition of metadata accessModeSufficient 

### ISSUE THREAD

**Issue by laudrain** [daisy/kb#6]
I am wondering why metadata accessModeSufficient has to be a list of different values ?
Like in:
```
<meta property="schema:accessMode">textual</meta>
<meta property="schema:accessMode">visual</meta>
<meta property="schema:accessModeSufficient">textual,visual</meta>
<meta property="schema:accessModeSufficient">textual</meta> 
```
When all images have been described, it should be _sufficient_ to say:
```
<meta property="schema:accessMode">textual</meta>
<meta property="schema:accessMode">visual</meta>
<meta property="schema:accessModeSufficient">textual</meta>
```

**Comment by mattgarrish** [comment]
Sufficient access modes lists all the possible combinations of sensory and perceptual abilities that can be used to access the information.

In the case you describe, if you can see and read the text, that's sufficient for reading the work. It's also sufficient for reading if you can access the text and alternatives. That's why two separate sets are listed.

In general, you can always assume one accessModeSufficient entry that is a combination of the accessMode values, but it still should be explicitly indicated so that users don't have to compute it themselves.

**Comment by laudrain** [comment]
Thanks, 
Indeed it is a must to say for blind people that:
`<meta property="schema:accessModeSufficient">textual</meta>`
For non visually impaired people, is it so useful to tell them that they see images and read the text?

But before users access the file, we have to explain to retailers/libraries what to display for these titles in their web sites, using ONIX a11y codes in list 196.
As you certainly know, there is no corresponding ONIX code for accessModeSufficient.
Or perhaps inside WCAG AA global conformance.

Nonetheless, I will do my best for retailers/libraries to display something that says:
`<meta property="schema:accessModeSufficient">textual</meta>`
But I am wondering how I will make them understand that they should alos display something that says:
`<meta property="schema:accessModeSufficient">textual,visual</meta>`

**Comment by mattgarrish** [comment]
Sufficient access modes is not about _alternatives_., though; it's all the possibilities for consuming the work.

Access modes tell you about the default nature of the content, but they don't necessarily tell you that you need to be able to consume all that content to fully access the information. The images might be superfluous for example, so even though there is visual content you can sufficiently read the work even if you can't see it and no alternatives are provided.

That's why I said it's only a general rule that there will be a list of all the access modes. The metadata still needs to be verified for accuracy. And that's why you should always provide the full list of sets, so someone can determine whether any specified access mode is important or not.

**Comment by laudrain** [comment]
Sorry but I am probably disturbed by the name of that property.
With 
`<meta property="schema:accessModeSufficient">textual</meta>`
I would have thought that "sufficient" means that whatever type of information in the content (textual, visual, auditory, tactile), text alternatives have been provided, then a textual access mode is enough to access all the content.
In terms of a11y, it is the most important and and probably the only thing to say to retailers/libraries.

Pragmatically, in a first (but perhaps wrong) approach, among all accessModeSufficient sets found in the EPUB file, I would check the minimum one to forward proper information downstream in the supply chain. 
That's in theory today, as accessModeSufficient is not (yet) implemented in ONIX...

**Comment by rdeltour** [comment]
> Sufficient access modes is not about alternatives., though; it's all the possibilities for consuming the work.

I think the confusion comes from these two specific modes (textual and visual), in that one seems to be **implied** by the other. Basically, it would be reasonable to expect that any book that can be accessed textually (an AT can access the full text), can also be accessed visually (eyes can see the full text).

But in practice, it seems that "visual" is not only used to indicate the _mode_ but also has implicit information that the _content_ contains graphics (charts, images, etc.).

Even if `textal,visual` is kinda implicit when you already have `textual`, I think it doesn't cost a lot to be thorough and add both.

**Comment by mattgarrish** [comment]
> I think the confusion comes from these two specific modes (textual and visual), in that one seems to be implied by the other.

Textual means that the content can be fully consumed in textual form, not necessarily that you have to read it with your eyes. As you say, it means an AT can access content that is available in textual form.

It's not true that visual content can be read in textual form, or that if you can consume textual content that you can also consume visual content, so you can't infer one from the other.

I think what might be confusing is that this issue is only looking at one dimension: sighted reading. Consider adding auditory to the list for embedded video or audio clips. The possible modes for reading such content becomes more complex, and isn't only about whether you can see the content.

That's why the property is used to define all the possible combinations that can be used, not selectively choose what modes are considered "accessible".

**Comment by laudrain** [comment]
I'll try to put it in another way to see if I've understood.

Let 's say an EPUB has text and images, only. The author of the EPUB has tagged all images with role="decoration" as they do not bear any meaningfull content.
Then this should be fine:
```
<meta property="schema:accessMode">textual</meta>
<meta property="schema:accessMode">visual</meta>
<meta property="schema:accessModeSufficient">textual</meta>
```
Even, Ace should report a violation in that case if there a line with:
```
<meta property="schema:accessModeSufficient">visual,textual</meta>
```

On the contrary, if there at least one image that is not tagged role="decoration", Ace should report a violation if that line with "accessModeSufficient visual,textual" is missing !

**Comment by mattgarrish** [comment]
> Let 's say an EPUB has text and images, only. ... Then this should be fine:

Yes, if all the images are decorative than only listing a textual access mode is fine.

> Even, Ace should report a violation in that case if there a line with:

Yes, I don't know that Ace checks that deeply, but it probably should question why "textual,visual" is specified when no meaningful images were found.

> On the contrary, if there at least one image that is not tagged role="decoration", Ace should report a violation if that line with "accessModeSufficient visual,textual" is missing

Right, because one possible way to read the content is through a combination of text and visual comprehension. That's the one set that's usually can be inferred, and I think Ace would recommend it.

Whether there should also a second entry for "textual" would again be hard for Ace to determine. Just because someone has added alt text, for example, doesn't mean that a user can meaningfully access all the same information as someone who can see the images. What combinations of modes allow a user to fully consume the information requires a certain measure of interpretation by the person recording the metadata.

The problem with assuming that you can omit certain sets because they seem obvious is that it complicates how to apply the property in less apparent situations. The rule is to list all of them, not selectively remove ones that you assume "mainstream" audiences won't be interested in.

If it helps, keep in mind that each accessModeSufficient entry is completely independent of every other. You're not compiling information from all of them, or looking for the lowest common base.

If you want a more complicated example, consider a read-aloud book. It could have the following two entries:

```
<meta property="schema:accessModeSufficient">textual</meta>
<meta property="schema:accessModeSufficient">auditory</meta>
```

Which of these gets dropped? They're both viable means of accessing the content.

**Comment by rdeltour** [comment]
> It's not true that visual content can be read in textual form, or that if you can consume textual content that you can also consume visual content, so you can't infer one from the other.

Of course!

What I meant is that if `textual` is sufficient, then `textual,visual` (which is a superset of the former) is necessarily sufficient as well; this can be inferred. No?

> The problem with assuming that you can omit certain sets because they seem obvious is that it complicates how to apply the property in less apparent situations. The rule is to list all of them, not selectively remove ones that you assume "mainstream" audiences won't be interested in.

I fully agree, which is why I said that all modes should be made explicit, even if some could be inferred, like in the case above.

**Comment by mattgarrish** [comment]
> What I meant is that if textual is sufficient, then textual,visual (which is a superset of the former) is necessarily sufficient as well; this can be inferred. No?

That's the thing. In general, you can assume that one set will be the combination of all the access modes. It's not going to be common that it wouldn't be, but there are exceptions like the read aloud book example I cited.

But it also makes it harder for the user to gather the information, and harder for it to be searched on, when it has to be gleaned from other metadata properties. It's a whole lot simpler just to list all the possible combinations than get into the complexity of explaining to people when sets can be excluded and when they can be inferred or not. It'll lead to mistakes.

**Comment by mattgarrish** [comment]
It's also helpful to be explicit about all the sets because it indicates that you've actually considered the metadata. We're assuming that the property is only set for accessible content, but we want this metadata included in any content. If no sufficient access modes are listed, can you be sure the book been checked? If only "textual,visual" is listed, at least you have a sense that the book is not going to be useful to you if you need a purely textual access mode.

**Comment by rdeltour** [comment]
> In general, you can assume that one set will be the combination of all the access modes. It's not going to be common that it wouldn't be, but there are exceptions like the read aloud book example I cited.

I believe we agree on the principle that all sufficient modes should be explicitly listed…
but, for the sake of clarity, in the read-aloud example, wouldn’t `textual,auditory` be listed as a sufficient access mode as well?

**Comment by mattgarrish** [comment]
> wouldn’t textual,auditory be listed as a sufficient access mode as well?

Yes, I'm mixing up old use cases. If they aren't synchronized, then it's textual or auditory, but you do list both if they are synchonized.

At any rate, I'm closing this issue as unrelated to the knowledge base. If you want to change how the property is used, @laudrain , please raise it during the next revision of the accessibility specification. The techniques document also says to list all possible combinations, and if this practice is changed we'd need to make sure that all interested parties are in agreement.
