### ISSUE TITLE
page breaks at the beginning of a chapter

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/kb#76]
We have come across this problem. Often at the beginning of a chapter we find a structure like:

```
<section>
    <h1><span role="doc-pagebreak" aria-label="11" />Chapter 1</h1>
    ...
```

This structure leads to a problem since the accessible name of the heading becomes "11 Chapter 1". This accessible name can be  misleading for example when the end user navigate the page by headings.

What suggestions are there for handling these situations?

**Comment by mattgarrish** [comment]
Yes, I came across the same thing in a private discussion. I'm actually in the middle of splitting up the page navigation page and adding a faq about this to the new page breaks page. I'm hoping to have it ready to publish later today.

There's no reason for the page break to be inside the h1. It's not part of the heading, and I'm not sure what value there is in having people jump straight into the heading. The page break should be before the heading tag so that the heading is the first piece of content read after using the page list to get to the page. I assume that's the same guidance you're giving?

**Comment by gregoriopellegrino** [comment]
I think the fear of pagebreak before heading is that this creates a white space, but from some tests it seems to me that this is not the case.

**Comment by mattgarrish** [comment]
> but from some tests it seems to me that this is not the case.

Right, it's an empty element so there's no space to add. Even if you were to change it to a div it wouldn't affect the layout.
